### ISSUE TITLE
A terrible experience

### ISSUE THREAD

**Issue by pedro2555** [flathub/com.mojang.Minecraft#77] opened 2021-03-06 16:57 UTC
My machine is rather powerful, however this takes anything from 5 to 30 minutes to load a world, sometimes not at all. Crashes randomly with OOM errors even on the simplest of maps. Often gets stuck while loading a world. And none of this is specific to a world, is pretty much random.

Overall using this installation was a more painful experience than dealing with the java runtime issues, at least those are rather simple to understand.

This is unusable as it is.

**Comment by AsciiWolf** [comment] 2021-03-06 17:52
Hmm, this is strange. It works fine on any of my computers and from what I heard from other people, it works fine on theirs as well. What HW/OS configuration do you have?

**Comment by teh404guy** [comment] 2021-03-08 14:01
@pedro2555 Out of memory errors means not enough ram is located so make sure you have atleast 3gb free on your system

**Comment by AsciiWolf** [comment] 2021-03-22 11:36
Since there were no additional information provided and I was not able to reproduce the issue, I am closing this ticket. Feel free to reopen if you find more information about what could be causing this issue. Thanks!

**Comment by pedro2555** [comment] 2021-03-22 11:58
Hi. Sorry, too busy at work. The problem seems way less frequent after a `flatpak update`. Thanks.

The machine is:

Quad-Core Intel® Core™ i7-10510U CPU @ 1.80GHz
Intel Corporation UHD Graphics (rev 02)
NVIDIA Corporation GP108M [GeForce MX330] (rev a1)   <-- The one in use
7,9 GB memory
241,0 GB storage (NVMe SSD)

The OS is:
elementary OS 5.1.7 Hera
Built on Ubuntu 18.04.4 LTS
Linux 5.4.0-67-generic
GTK 3.22.30

**Comment by pedro2555** [comment] 2021-03-22 12:42
> @pedro2555 Out of memory errors means not enough ram is located so make sure you have atleast 3gb free on your system

Yes. The thing is, there was plenty of ram available. Is there a possibility this is actually VRAM?

**Comment by pedro2555** [comment] 2021-03-22 13:12
@AsciiWolf I guess you can keep this closed. The problem seems way less frequent, while at the same time I had very little time to play at all. But I did do a flatpak update with the latest os updates. Since then I played a few times, and I'm yet to see any problem.

If I get further problems I will get back to this issue.

**Comment by AsciiWolf** [comment] 2021-03-22 15:34
Ok, thanks!

**Closed by AsciiWolf** 2021-03-22 15:34 UTC
