### ISSUE TITLE
Minecraft 1.17: OptiFine: liblwjgl.so not found in java.library.path

### ISSUE THREAD

**Issue by sebastian-philipp** [flathub/com.mojang.Minecraft#81] opened 2021-06-11 19:50 UTC
when running minecraft 1.17 with optifine: 

```
<log4j:Event logger="LaunchWrapper" timestamp="1623440205110" level="INFO" thread="main">
    <log4j:Message><![CDATA[Loading tweak class name optifine.OptiFineTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1623440205113" level="INFO" thread="main">
    <log4j:Message><![CDATA[Using primary tweak class name optifine.OptiFineTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1623440205113" level="INFO" thread="main">
    <log4j:Message><![CDATA[Calling tweak class optifine.OptiFineTweaker]]></log4j:Message>
  </log4j:Event>
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: /home/sebastian/.var/app/com.mojang.Minecraft/data/minecraft/libraries/optifine/OptiFine/1.17_HD_U_G9_pre20/OptiFine-1.17_HD_U_G9_pre20.jar
OptiFineTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
  <log4j:Event logger="LaunchWrapper" timestamp="1623440205334" level="INFO" thread="main">
    <log4j:Message><![CDATA[Launching wrapped minecraft {net.minecraft.client.main.Main}]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1623440207983" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1623440208057" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1623440208057" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1623440208057" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1623440208066" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1623440211179" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService" timestamp="1623440211536" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD']]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="dvo" timestamp="1623440212874" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Setting user: TheHammer2000]]></log4j:Message>
  </log4j:Event>
[LWJGL]   <log4j:Event logger="xd" timestamp="1623440213017" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: Version: 3.2.2 build 10]]></log4j:Message>
  </log4j:Event>
[LWJGL]   <log4j:Event logger="xd" timestamp="1623440213017" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]:    OS: Linux v5.11.20-200.fc33.x86_64]]></log4j:Message>
  </log4j:Event>
[LWJGL]   <log4j:Event logger="xd" timestamp="1623440213017" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]:   JRE: 16.0.1 amd64]]></log4j:Message>
  </log4j:Event>
[LWJGL]   <log4j:Event logger="xd" timestamp="1623440213018" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]:   JVM: OpenJDK 64-Bit Server VM v16.0.1+9 by Microsoft]]></log4j:Message>
  </log4j:Event>
[LWJGL]   <log4j:Event logger="xd" timestamp="1623440213024" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: Loading library (system): lwjgl]]></log4j:Message>
  </log4j:Event>
[LWJGL]   <log4j:Event logger="xd" timestamp="1623440213025" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]:   liblwjgl.so not found in java.library.path]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="xd" timestamp="1623440213025" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1623440213131" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Unable to launch]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
        at com.mojang.blaze3d.platform.GLX.getOpenGLVersionString(GLX.java:38)
        at com.mojang.blaze3d.systems.RenderSystem.getApiDescription(RenderSystem.java:593)
        at ac.a(SourceFile:65)
        at dvo.a(SourceFile:2418)
        at dvo.a(SourceFile:2412)
        at net.minecraft.client.main.Main.main(SourceFile:187)
        ... 6 more
]]></log4j:Throwable>
  </log4j:Event>
```

And indeed: `cd .var ; find * -name 'liblwjgl.so'` returns nothing.

**Comment by AsciiWolf** [comment] 2021-07-08 18:14
I think that this will be fixed after #83 is merged - latest Minecraft Launcher now uses bundled Java.

**Comment by AsciiWolf** [comment] 2021-07-10 19:54
@sebastian-philipp Could you please re-test this and let us know whether the latest Flatpak build (that will be available in a few hours) fixes the issue? Thanks!

**Comment by SystemlessDev** [comment] 2021-09-05 21:40
Cannot reproduce this issue on my side. The log that was provided above makes me suspect that it's just optifine being optifine.

**Comment by SystemlessDev** [comment] 2022-11-13 20:06
This is caused by OptiFine. It's not related to the flatpak package.

**Closed by SystemlessDev** 2022-11-13 20:06 UTC
